apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: hyper-ops.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: A small controller that creates ArgoCD clusters from hypershift hosted
    clusters
  displayName: HyperOps
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - argocd
  - hypershift
  links:
  - name: Hyper Ops
    url: https://hyper-ops.domain
  maintainers:
  - email: mbengtss@redhat.com
    name: name1
  maturity: alpha
  provider:
    name: HyperOps
  version: 0.0.0
